# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 03:56
from __future__ import unicode_literals

import Posts.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.FileField(upload_to=Posts.models.get_file_name, validators=[Posts.models.validate_file_extension])),
                ('auto_delete', models.BooleanField(default=True, help_text='Auto Delete image unoptimized when uploaded.')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 11, 20, 3, 56, 50, 768010, tzinfo=utc))),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
