# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 03:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 3, 57, 0, 875694, tzinfo=utc)),
        ),
    ]
