# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 07:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20181120_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 7, 44, 46, 588995, tzinfo=utc)),
        ),
    ]
