# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 03:18
from __future__ import unicode_literals

import Posts.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_auto_20181114_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 3, 18, 37, 140679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=Posts.models.get_file_name, validators=[Posts.models.validate_file_extension]),
        ),
    ]
