# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 08:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_auto_20181120_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 8, 33, 3, 726520, tzinfo=utc)),
        ),
    ]
