# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 10:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_auto_20181120_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 10, 0, 2, 175777, tzinfo=utc)),
        ),
    ]
