# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 03:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_auto_20181116_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auto_delete',
            field=models.BooleanField(default=True, help_text='Auto Delete image unoptimized when uploaded.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 3, 27, 20, 9756, tzinfo=utc)),
        ),
    ]
