# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 08:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_auto_20181116_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 8, 43, 53, 129949, tzinfo=utc)),
        ),
    ]
