# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 07:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_auto_20181126_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 7, 18, 16, 185903, tzinfo=utc)),
        ),
    ]
