# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 07:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0011_auto_20181128_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 28, 7, 21, 44, 765298, tzinfo=utc)),
        ),
    ]
